spring:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    platform: mysql
    hikari:
      poolName: Hikari
      auto-commit: true
    url: jdbc:mysql://localhost:3306/helloworld?createDatabaseIfNotExist=true&characterEncoding=utf8&useSSL=false&useLegacyDatetimeCode=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: root
    password: admin

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
        jdbc:
          time_zone: UTC

# spring.datasource.username = <yourUserName>